version: 2

workflows:
  version: 2
  test:
    jobs:
      - frontend-bundle_npm_dependencies
      - frontend-test:
          requires:
            - frontend-bundle_npm_dependencies

jobs:
  frontend-bundle_npm_dependencies:
    docker:
      - image: circleci/node:10
    working_directory: ~/rails-react-typescript-docker-example
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "frontend/yarn.lock" }}
            - npm-v1-dependencies-
      - run:
          name: yarn install
          command: |
            cd frontend
            yarn install
      - save_cache:
          paths:
            - ~/rails-react-typescript-docker-example/frontend/node_modules
          key: npm-v1-dependencies-{{ checksum "frontend/yarn.lock" }}

  frontend-test:
    docker:
      - image: circleci/node:10
    working_directory: ~/rails-react-typescript-docker-example
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "frontend/yarn.lock" }}
            - npm-v1-dependencies-
      - run:
          name: tests
          command: |
            cd frontend
            yarn test
